---
resource_types:
  - name: pull-request
    type: docker-image
    check_every: 5m
    source:
      repository: jtarchie/pr
      username: {{dockerhub_username}}
      password: {{dockerhub_password}}

resources:
  - name: master
    type: git
    source:
      uri: {{cerego_docker_repo}}
      branch: master
      private_key: {{cerebot-github-priv-key}}
  - name: s3-resource-simple-repo
    type: git
    source:
      uri: git@github.com:ceregousa/s3-resource-simple.git
      branch: master
      private_key: {{cerebot-github-priv-key}}
  - name: pr
    type: pull-request
    source:
      repo: ceregousa/docker-images
      access_token: {{cerebot-access-token}}
      uri: {{cerego_docker_repo}}
      private_key: {{cerebot-github-priv-key}}
  - name: dind
    type: docker-image
    check_every: 24h
    source:
      repository: ceregousa/dind
      tag: docker-1.13
      username: {{dockerhub_username}}
      password: {{dockerhub_password}}
  - name: ubuntu-git
    type: docker-image
    check_every: 24h
    source:
      repository: ceregousa/ubuntu-git
      username: {{dockerhub_username}}
      password: {{dockerhub_password}}
  - name: s3-resource-simple
    type: docker-image
    check_every: 24h
    source:
      repository: ceregousa/s3-resource-simple
      username: {{dockerhub_username}}
      password: {{dockerhub_password}}

jobs:
  - name: PR builder
    build_logs_to_retain: 20
    plan:
      - get: pr
        params: {git.depth: 1}
        trigger: true
        version: every
      - put: pr
        params: { path: pr, status: pending }
      - aggregate:
        - put: dind
          params: { build: pr/dind, tag: pr/ci/tags/test }
        - put: ubuntu-git
          params: { build: pr/ubuntu-git, tag: pr/ci/tags/test }
    on_success:
      put: pr
      params: { path: pr, status: success }
    on_failure:
      put: pr
      params: { path: pr, status: failure }
  - name: build dind
    build_logs_to_retain: 10
    plan:
      - get: master
        params: {depth: 1}
        trigger: true
      - put: dind
        params: { build: master/dind, tag_as_latest: true }
  - name: build ubuntu-git
    build_logs_to_retain: 10
    plan:
      - get: master
        params: {depth: 1}
        trigger: true
      - put: ubuntu-git
        params: { build: master/ubuntu-git, tag_as_latest: true }
  - name: build s3-resource-simple
    build_logs_to_retain: 10
    plan:
      - get: s3-resource-simple-repo
        trigger: true
      - put: s3-resource-simple
        params: { build: s3-resource-simple-repo, tag_as_latest: true }
