---
resources:
  - name: master
    type: git
    source:
      uri: git@github.com:ceregousa/dind.git
      branch: master
      private_key: {{cerebot-github-priv-key}}
  - name: dind
    type: docker-image
    source:
      repository: ceregousa/dind
      tag: ruby-2.2
      username: {{dockerhub_username}}
      password: {{dockerhub_password}}

jobs:
  - name: create image
    build_logs_to_retain: 10
    plan:
      - get: master
        trigger: true
      - put: dind
        params: { build: master, tag_as_latest: true }
